//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SENNOVAContainer : DbContext
    {
        public DB_SENNOVAContainer()
            : base("name=DB_SENNOVAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblProyecto> tblProyecto { get; set; }
        public virtual DbSet<tblRegion> tblRegion { get; set; }
        public virtual DbSet<tblRegional> tblRegional { get; set; }
        public virtual DbSet<tblCentroFormacion> tblCentroFormacion { get; set; }
        public virtual DbSet<tblLineaProgramatica> tblLineaProgramatica { get; set; }
        public virtual DbSet<tblAreaConocimiento> tblAreaConocimiento { get; set; }
        public virtual DbSet<tblRolSennova> tblRolSennova { get; set; }
        public virtual DbSet<tblRedConocimientoSectorial> tblRedConocimientoSectorial { get; set; }
        public virtual DbSet<tblPersona> tblPersona { get; set; }
        public virtual DbSet<tblTipoDocumento> tblTipoDocumento { get; set; }
        public virtual DbSet<tblObjetivoEspecifico> tblObjetivoEspecifico { get; set; }
        public virtual DbSet<tblActividad> tblActividad { get; set; }
        public virtual DbSet<tblProducto> tblProducto { get; set; }
        public virtual DbSet<tblTipoProducto> tblTipoProducto { get; set; }
        public virtual DbSet<tblAvanceProyecto> tblAvanceProyecto { get; set; }
        public virtual DbSet<tblRubro> tblRubro { get; set; }
        public virtual DbSet<tblProyectoRubro> tblProyectoRubro { get; set; }
        public virtual DbSet<tblIngreso> tblIngreso { get; set; }
        public virtual DbSet<tblAreaTecnica> tblAreaTecnica { get; set; }
        public virtual DbSet<tblTipoAreaTecnica> tblTipoAreaTecnica { get; set; }
        public virtual DbSet<tblServicio> tblServicio { get; set; }
        public virtual DbSet<tblIngresosAreasTecnicas> tblIngresosAreasTecnicas { get; set; }
        public virtual DbSet<tblProgramaFormacion> tblProgramaFormacion { get; set; }
        public virtual DbSet<tblEmpleado> tblEmpleado { get; set; }
        public virtual DbSet<tblVisitante> tblVisitante { get; set; }
        public virtual DbSet<tblTipoVisitante> tblTipoVisitante { get; set; }
        public virtual DbSet<tblEmpresa> tblEmpresa { get; set; }
        public virtual DbSet<tblSectorEconomico> tblSectorEconomico { get; set; }
        public virtual DbSet<tblDocumento> tblDocumento { get; set; }
        public virtual DbSet<tblTiposDocumentos> tblTiposDocumentos { get; set; }
        public virtual DbSet<tblMacroProcesos> tblMacroProcesos { get; set; }
        public virtual DbSet<tblProcesos> tblProcesos { get; set; }
        public virtual DbSet<tblProcedimiento> tblProcedimiento { get; set; }
        public virtual DbSet<tblDetallesDocumento> tblDetallesDocumento { get; set; }
        public virtual DbSet<tblImpresora> tblImpresora { get; set; }
        public virtual DbSet<tblSoftware> tblSoftware { get; set; }
        public virtual DbSet<tblTipoLicencia> tblTipoLicencia { get; set; }
        public virtual DbSet<tblTipoEquipo> tblTipoEquipo { get; set; }
        public virtual DbSet<tblEquipo> tblEquipo { get; set; }
        public virtual DbSet<tblEquipoSoftware> tblEquipoSoftware { get; set; }
        public virtual DbSet<tblCalibracion> tblCalibracion { get; set; }
        public virtual DbSet<tblMantenimiento> tblMantenimiento { get; set; }
        public virtual DbSet<tblMantenimientoEquipo> tblMantenimientoEuipo { get; set; }
        public virtual DbSet<tblCalibracionEquipo> tblCalibracionEquipo { get; set; }
        public virtual DbSet<tblComputo> tblComputo { get; set; }
        public virtual DbSet<tblEquipoTecnico> tblEquipoTecnico { get; set; }
        public virtual DbSet<tblTipoPatron> tblTipoPatron { get; set; }
        public virtual DbSet<tblAccesorios> tblAccesorios { get; set; }
        public virtual DbSet<tblEquipoAccesorio> tblEquipoAccesorio { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblDetallesDocumentoSet> tblDetallesDocumentoSet { get; set; }
        public virtual DbSet<tblCotizacion> tblCotizacion { get; set; }
        public virtual DbSet<tblTerminoCondicion> tblTerminoCondicion { get; set; }
        public virtual DbSet<tblTerminoCotizacion> tblTerminoCotizacion { get; set; }
        public virtual DbSet<tblCotizacionDetalle> tblCotizacionDetalle { get; set; }
        public virtual DbSet<tblCliente> tblCliente { get; set; }
        public virtual DbSet<tblCargo> tblCargo { get; set; }
        public virtual DbSet<tblOrdenTrabajo> tblOrdenTrabajo { get; set; }
        public virtual DbSet<tblOrdenTrabajoDetalles> tblOrdenTrabajoDetalles { get; set; }
        public virtual DbSet<tblFamilia> tblFamilia { get; set; }
    }
}
