//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCotizacionDetalle
    {
        public int Id { get; set; }
        public Nullable<decimal> PrecioServicio { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public string Observaciones { get; set; }
    
        public virtual tblCotizacion tblCotizacion { get; set; }
        public virtual tblServicio tblServicio { get; set; }
    }
}
