//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComputo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComputo()
        {
            this.lstEquipoSoftware = new HashSet<tblEquipoSoftware>();
        }
    
        public int Id { get; set; }
        public string Ip { get; set; }
        public Nullable<bool> CuentaAdmin { get; set; }
        public Nullable<bool> Backup { get; set; }
        public string Procesador { get; set; }
        public string Ram { get; set; }
        public string Disco { get; set; }
        public string Observaciones { get; set; }
    
        public virtual tblEquipo tblEquipo { get; set; }
        public virtual tblImpresora tblImpresora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipoSoftware> lstEquipoSoftware { get; set; }
    }
}
