//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleado()
        {
            this.lstProyecto = new HashSet<tblProyecto>();
            this.lstAreaTecnicas = new HashSet<tblAreaTecnica>();
            this.lstIngresos = new HashSet<tblIngreso>();
            this.lstDetallesDocumentosSolicitados = new HashSet<tblDetallesDocumento>();
            this.lstDetallesDocumentosRevisados = new HashSet<tblDetallesDocumento>();
            this.lstDetallesDocumentosAprovados = new HashSet<tblDetallesDocumento>();
            this.lstEquipos = new HashSet<tblEquipo>();
            this.lstMantenimientos = new HashSet<tblMantenimiento>();
            this.tblMantenimiento = new HashSet<tblMantenimiento>();
            this.lstCotizacionesSolicitante = new HashSet<tblCotizacion>();
            this.lstCotizacionesAutorizador = new HashSet<tblCotizacion>();
            this.lstCotizacionesRevisador = new HashSet<tblCotizacion>();
            this.lstOrdenesTrabajos = new HashSet<tblOrdenTrabajo>();
        }
    
        public int Id { get; set; }
        public string EmailLaboral { get; set; }
        public string Telefono { get; set; }
        public string Ip { get; set; }
    
        public virtual tblPersona tblPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyecto> lstProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAreaTecnica> lstAreaTecnicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngreso> lstIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesDocumento> lstDetallesDocumentosSolicitados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesDocumento> lstDetallesDocumentosRevisados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesDocumento> lstDetallesDocumentosAprovados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipo> lstEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMantenimiento> lstMantenimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMantenimiento> tblMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCotizacion> lstCotizacionesSolicitante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCotizacion> lstCotizacionesAutorizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCotizacion> lstCotizacionesRevisador { get; set; }
        public virtual tblCargo tblCargo { get; set; }
        public virtual tblRolSennova tblRolSennova { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdenTrabajo> lstOrdenesTrabajos { get; set; }
    }
}
