//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEquipo()
        {
            this.lstMantenimientoEquipos = new HashSet<tblMantenimientoEquipo>();
            this.lstCalibracionEquipos = new HashSet<tblCalibracionEquipo>();
            this.lstComputos = new HashSet<tblComputo>();
            this.lstEquipoTecnicos = new HashSet<tblEquipoTecnico>();
            this.lstEquipoAccesorios = new HashSet<tblEquipoAccesorio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Placa { get; set; }
        public string Serial { get; set; }
        public string Marca { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal Valor { get; set; }
        public string NumeroContrato { get; set; }
        public System.DateTime FechaFuncionamiento { get; set; }
    
        public virtual tblEmpleado Responsable { get; set; }
        public virtual tblAreaTecnica tblAreaTecnica { get; set; }
        public virtual tblTipoEquipo tblTipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMantenimientoEquipo> lstMantenimientoEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCalibracionEquipo> lstCalibracionEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComputo> lstComputos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipoTecnico> lstEquipoTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipoAccesorio> lstEquipoAccesorios { get; set; }
    }
}
