//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIngreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIngreso()
        {
            this.lstIngresosAreasTecnicas = new HashSet<tblIngresosAreasTecnicas>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> PoliticaDatos { get; set; }
        public string Ficha { get; set; }
    
        public virtual tblVisitante tblVisitante { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblProgramaFormacion tblProgramaFormacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngresosAreasTecnicas> lstIngresosAreasTecnicas { get; set; }
        public virtual tblEmpleado tblEmpleado { get; set; }
    }
}
