//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProyecto()
        {
            this.lstObjetivoEspecificos = new HashSet<tblObjetivoEspecifico>();
            this.lstProyectoRubros = new HashSet<tblProyectoRubro>();
        }
    
        public int Id { get; set; }
        public string TituloProyecto { get; set; }
        public string CodigoSGPS { get; set; }
        public short AnoEjecucion { get; set; }
        public System.DateTime FechaDiligenciamiento { get; set; }
        public string ObjetivoGeneral { get; set; }
        public decimal AsignacionInicial { get; set; }
        public Nullable<decimal> TotalAdiciones { get; set; }
        public Nullable<decimal> TotalDisminucionesCentralizaciones { get; set; }
        public Nullable<decimal> TotalEjecutado { get; set; }
        public Nullable<decimal> PresupuestoFinal { get; set; }
    
        public virtual tblCentroFormacion tblCentroFormacion { get; set; }
        public virtual tblLineaProgramatica tblLineaProgramatica { get; set; }
        public virtual tblRedConocimientoSectorial tblRedConocimientoSectorial { get; set; }
        public virtual tblAreaConocimiento tblAreaConocimiento { get; set; }
        public virtual tblEmpleado tblEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblObjetivoEspecifico> lstObjetivoEspecificos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyectoRubro> lstProyectoRubros { get; set; }
    }
}
