//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class SettingsMessage : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsMessage defaultInstance = ((SettingsMessage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsMessage())));
        
        public static SettingsMessage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Persona no existe !")]
        public string PersonaNull {
            get {
                return ((string)(this["PersonaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo Documento no existe !")]
        public string TipoDocumentoNull {
            get {
                return ((string)(this["TipoDocumentoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Region no existe !")]
        public string RegionNull {
            get {
                return ((string)(this["RegionNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Regional no existe !")]
        public string RegionalNull {
            get {
                return ((string)(this["RegionalNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Codigo no puede estar vacio !")]
        public string CodigoVacio {
            get {
                return ((string)(this["CodigoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Nombre no puede estar vacio !")]
        public string NombreVacio {
            get {
                return ((string)(this["NombreVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Direccion no puede estar vacio !")]
        public string DireccionVacio {
            get {
                return ((string)(this["DireccionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Telefono no puede estar vacio !")]
        public string TelefonoVacio {
            get {
                return ((string)(this["TelefonoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Email no puede estar vacio !")]
        public string EmailVacio {
            get {
                return ((string)(this["EmailVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Apellidos no puede estar vacio !")]
        public string ApellidosVacio {
            get {
                return ((string)(this["ApellidosVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Area de Conocimiento no existe !")]
        public string AreaConocimientoNull {
            get {
                return ((string)(this["AreaConocimientoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Centro de Formación no existe !")]
        public string CentroFormacionNull {
            get {
                return ((string)(this["CentroFormacionNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Linea Programatica no existe !")]
        public string LineaProgramaticaNull {
            get {
                return ((string)(this["LineaProgramaticaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Red de Conocimiento Sectorial no existe !")]
        public string RedConocimientoSectorialNull {
            get {
                return ((string)(this["RedConocimientoSectorialNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Rol SENNOVA no existe !")]
        public string RolSennovaNull {
            get {
                return ((string)(this["RolSennovaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo de Producto no existe !")]
        public string TipoProductoNull {
            get {
                return ((string)(this["TipoProductoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Tipo Producto no puede estar vacio !")]
        public string TipoProductoVacio {
            get {
                return ((string)(this["TipoProductoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Actividad no puede estar vacio !")]
        public string ActividadVacio {
            get {
                return ((string)(this["ActividadVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Producto no existe !")]
        public string ProductoNull {
            get {
                return ((string)(this["ProductoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Actividad no existe !")]
        public string ActividadNull {
            get {
                return ((string)(this["ActividadNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Proyecto no puede estar vacio !")]
        public string ProyectoVacio {
            get {
                return ((string)(this["ProyectoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Objetivo Especifico no existe !")]
        public string ObjetivoEspecificoNull {
            get {
                return ((string)(this["ObjetivoEspecificoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Proyecto no existe !")]
        public string ProyectoNull {
            get {
                return ((string)(this["ProyectoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Avance del Proyecto no existe !")]
        public string AvanceProyectoNull {
            get {
                return ((string)(this["AvanceProyectoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Mes no puede estar vacio !")]
        public string MesVacio {
            get {
                return ((string)(this["MesVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Proyectado no puede estar vacio !")]
        public string ProyectadoVacio {
            get {
                return ((string)(this["ProyectadoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Ejecutado no puede estar vacio !")]
        public string EjecutadoVacio {
            get {
                return ((string)(this["EjecutadoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Numero de Identificacion no puede estar vacio !")]
        public string numeroIdentificacionVacio {
            get {
                return ((string)(this["numeroIdentificacionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Ip no puede estar vacio !")]
        public string ipVacio {
            get {
                return ((string)(this["ipVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Tipo Documento no puede estar vacio !")]
        public string TipoDocumentoVacio {
            get {
                return ((string)(this["TipoDocumentoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Rol SENNOVA no puede estar vacio !")]
        public string RolSennovaVacio {
            get {
                return ((string)(this["RolSennovaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Se ha guardado correctamente !")]
        public string GuardoCorrecto {
            get {
                return ((string)(this["GuardoCorrecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los campos con (*) son obligatorios !")]
        public string CamposObligatorios {
            get {
                return ((string)(this["CamposObligatorios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Titulo no puede estar vacio !")]
        public string TituloProyecto {
            get {
                return ((string)(this["TituloProyecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Año de ejecución no puede estar vacio !")]
        public string AnoEjecucion {
            get {
                return ((string)(this["AnoEjecucion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Fecha no puede estar vacio !")]
        public string FechaDiligenciamiento {
            get {
                return ((string)(this["FechaDiligenciamiento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Objetivo no puede estar vacio !")]
        public string ObjetivoGeneralVacio {
            get {
                return ((string)(this["ObjetivoGeneralVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Asignación no puede estar vacio !")]
        public string AsignacionInicialVacio {
            get {
                return ((string)(this["AsignacionInicialVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Region no puede estar vacio !")]
        public string RegionVacio {
            get {
                return ((string)(this["RegionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Regional no puede estar vacio !")]
        public string RegionalVacio {
            get {
                return ((string)(this["RegionalVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Centro de Formación no puede estar vacio !")]
        public string CentroFormacionVacio {
            get {
                return ((string)(this["CentroFormacionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Linea Programatica no puede estar vacio !")]
        public string LineaProgramaticaVacio {
            get {
                return ((string)(this["LineaProgramaticaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Red de Conocimiento Sectorial no puede estar vacio !")]
        public string RedConocimientoSectorialVacio {
            get {
                return ((string)(this["RedConocimientoSectorialVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Area de Conocimiento no puede estar vacio !")]
        public string AreaConocimientoVacio {
            get {
                return ((string)(this["AreaConocimientoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Persona  no puede estar vacio !")]
        public string PersonaVacio {
            get {
                return ((string)(this["PersonaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/SoportesProductos/")]
        public string SoportesProductos {
            get {
                return ((string)(this["SoportesProductos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Rubro no puede estar vacio !")]
        public string RubroVacio {
            get {
                return ((string)(this["RubroVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Rubro no existe !")]
        public string RubroNull {
            get {
                return ((string)(this["RubroNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Objeto no puede estar vacio !")]
        public string ObjetoVacio {
            get {
                return ((string)(this["ObjetoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Valor no puede estar vacio !")]
        public string ValorVacio {
            get {
                return ((string)(this["ValorVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Proyecto Rubro no existe !")]
        public string ProyectoRubroNull {
            get {
                return ((string)(this["ProyectoRubroNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Proyecto Rubro no puede estar vacio !")]
        public string ProyectoRubroVacio {
            get {
                return ((string)(this["ProyectoRubroVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Empleado no existe !")]
        public string EmpleadoNull {
            get {
                return ((string)(this["EmpleadoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Empleado no puede estar vacio !")]
        public string EmpleadoVacio {
            get {
                return ((string)(this["EmpleadoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Area Tecnica no puede estar vacio !")]
        public string AreaTecnicaVacio {
            get {
                return ((string)(this["AreaTecnicaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Area Tecnica no existe !")]
        public string AreaTecnicaNull {
            get {
                return ((string)(this["AreaTecnicaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Ingreso Area Tecnica no existe !")]
        public string IngresosAreasTecnicasNull {
            get {
                return ((string)(this["IngresosAreasTecnicasNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Ingreso Area Tecnica no puede estar vacio !")]
        public string IngresosAreasTecnicasVacio {
            get {
                return ((string)(this["IngresosAreasTecnicasVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Ingreso no puede estar vacio !")]
        public string IngresoVacio {
            get {
                return ((string)(this["IngresoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Ingreso no existe !")]
        public string IngresoNull {
            get {
                return ((string)(this["IngresoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Programa de Formacion no existe !")]
        public string ProgramaFormacionNull {
            get {
                return ((string)(this["ProgramaFormacionNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo  Programa de Formacion no puede estar vacio !")]
        public string ProgramaFormacionVacio {
            get {
                return ((string)(this["ProgramaFormacionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Sector Economico no existe !")]
        public string SectorEconomicoNull {
            get {
                return ((string)(this["SectorEconomicoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo  Sector Economico no puede estar vacio !")]
        public string SectorEconomicoVacio {
            get {
                return ((string)(this["SectorEconomicoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Ingreso no existe !")]
        public string ServicioNull {
            get {
                return ((string)(this["ServicioNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo  Servicio no puede estar vacio !")]
        public string ServicioVacio {
            get {
                return ((string)(this["ServicioVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo Visitante no existe !")]
        public string TipoVisitanteNull {
            get {
                return ((string)(this["TipoVisitanteNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo  Tipo Visitante no puede estar vacio !")]
        public string TipoVisitanteVacio {
            get {
                return ((string)(this["TipoVisitanteVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo Area Tecnica no existe !")]
        public string TipoAreaTecnicaNull {
            get {
                return ((string)(this["TipoAreaTecnicaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo  Tipo Area Tecnica no puede estar vacio !")]
        public string TipoAreaTecnicaVacio {
            get {
                return ((string)(this["TipoAreaTecnicaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Visitante no puede estar vacio !")]
        public string VisitanteNull {
            get {
                return ((string)(this["VisitanteNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Visitante no existe !")]
        public string VisitanteVacio {
            get {
                return ((string)(this["VisitanteVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Fecha no puede estar vacio !")]
        public string FechaVacio {
            get {
                return ((string)(this["FechaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Politica de Datos no puede estar vacio !")]
        public string PoliticaDatosVacio {
            get {
                return ((string)(this["PoliticaDatosVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Razon Social no puede estar vacio !")]
        public string RazonSocialVacio {
            get {
                return ((string)(this["RazonSocialVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Nit no puede estar vacio !")]
        public string NitVacio {
            get {
                return ((string)(this["NitVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Empresa no existe !")]
        public string EmpresaNull {
            get {
                return ((string)(this["EmpresaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Empresa no puede estar vacio !")]
        public string EmpresaVacio {
            get {
                return ((string)(this["EmpresaVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Versión no puede estar vacio !")]
        public string VersionVacio {
            get {
                return ((string)(this["VersionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Ruta no puede estar vacio !")]
        public string RutaDocVacio {
            get {
                return ((string)(this["RutaDocVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Documento no puede estar vacio !")]
        public string DocumentoVacio {
            get {
                return ((string)(this["DocumentoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Documento no existe !")]
        public string DocumentoNull {
            get {
                return ((string)(this["DocumentoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Solicitante no puede estar vacio !")]
        public string SolicitanteVacio {
            get {
                return ((string)(this["SolicitanteVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Revisor no puede estar vacio !")]
        public string RevisorVacio {
            get {
                return ((string)(this["RevisorVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Aprovador no puede estar vacio !")]
        public string AprovadorVacio {
            get {
                return ((string)(this["AprovadorVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Macro Proceso no existe !")]
        public string MacroProcesoNull {
            get {
                return ((string)(this["MacroProcesoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Macro Proceso no puede estar vacio !")]
        public string MacroProcesoVacio {
            get {
                return ((string)(this["MacroProcesoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Procedimiento no existe !")]
        public string ProcedimientoNull {
            get {
                return ((string)(this["ProcedimientoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Procedimiento no puede estar vacio !")]
        public string ProcedimientoVacio {
            get {
                return ((string)(this["ProcedimientoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Proceso no existe !")]
        public string ProcesoNull {
            get {
                return ((string)(this["ProcesoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Proceso no puede estar vacio !")]
        public string ProcesoVacio {
            get {
                return ((string)(this["ProcesoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los Detalles del Documento no existe !")]
        public string DetallesDocumentoNull {
            get {
                return ((string)(this["DetallesDocumentoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo de Equipo no existe !")]
        public string TipoEquipoNull {
            get {
                return ((string)(this["TipoEquipoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo de Licencia no existe !")]
        public string TipoLicenciaNull {
            get {
                return ((string)(this["TipoLicenciaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Tipo de Patron no existe !")]
        public string TipoPatronNull {
            get {
                return ((string)(this["TipoPatronNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Impresora no existe !")]
        public string ImpresoraNull {
            get {
                return ((string)(this["ImpresoraNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Software no existe !")]
        public string SoftwareNull {
            get {
                return ((string)(this["SoftwareNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Equipo no existe !")]
        public string EquipoNull {
            get {
                return ((string)(this["EquipoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Equipo Computo no existe !")]
        public string ComputoNull {
            get {
                return ((string)(this["ComputoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Equipo Computo no puede estar vacio !")]
        public string ComputoVacio {
            get {
                return ((string)(this["ComputoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Software no puede estar vacio !")]
        public string SoftwareVacio {
            get {
                return ((string)(this["SoftwareVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Equipo Software no existe !")]
        public string EquipoSoftwareNull {
            get {
                return ((string)(this["EquipoSoftwareNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Equipo Tecnico no existe !")]
        public string EquipoTecnicoNull {
            get {
                return ((string)(this["EquipoTecnicoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Equipo no puede estar vacio !")]
        public string EquipoVacio {
            get {
                return ((string)(this["EquipoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Tipo de Patron no puede estar vacio !")]
        public string TipoPatronVacio {
            get {
                return ((string)(this["TipoPatronVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Equipo Técnico no puede estar vacio !")]
        public string EquipoTecnicoVacio {
            get {
                return ((string)(this["EquipoTecnicoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El AccesorioTecnico no existe !")]
        public string AccesoriosNull {
            get {
                return ((string)(this["AccesoriosNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Accesorio no puede estar vacio !")]
        public string AccesoriosVacio {
            get {
                return ((string)(this["AccesoriosVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Equipo AccesorioTecnico no existe !")]
        public string EquipoAccesorioNull {
            get {
                return ((string)(this["EquipoAccesorioNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Equipo Accesorio no puede estar vacio !")]
        public string EquipoAccesorioVacio {
            get {
                return ((string)(this["EquipoAccesorioVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Termino y condición no existe !")]
        public string TerminoCondicionNull {
            get {
                return ((string)(this["TerminoCondicionNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Termino y condición no puede estar vacio !")]
        public string TerminoCondicionVacio {
            get {
                return ((string)(this["TerminoCondicionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Cotización no existe !")]
        public string CotizacionNull {
            get {
                return ((string)(this["CotizacionNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Cargo no existe !")]
        public string CargoNull {
            get {
                return ((string)(this["CargoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Cargo no puede estar vacio !")]
        public string CargoVacio {
            get {
                return ((string)(this["CargoVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El mensaje se ha enviado exitozamente!")]
        public string CorreoEnviado {
            get {
                return ((string)(this["CorreoEnviado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Orden de trabajo no existe!")]
        public string OrdenTrabajoNull {
            get {
                return ((string)(this["OrdenTrabajoNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Número de orden de trabajo no puede estar vacio!")]
        public string NumeroOTVacio {
            get {
                return ((string)(this["NumeroOTVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Fecha emisión no puede estar vacio!")]
        public string FechaEmisionVacio {
            get {
                return ((string)(this["FechaEmisionVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Fecha limite no puede estar vacio!")]
        public string FechaLimiteVacio {
            get {
                return ((string)(this["FechaLimiteVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Fecha ingreso de orden de trabajo e item de servicio no puede estar vaci" +
            "o!")]
        public string FechaIngresoItemVacio {
            get {
                return ((string)(this["FechaIngresoItemVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Cantidad no puede estar vacio!")]
        public string CantidadVacio {
            get {
                return ((string)(this["CantidadVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Precio del servicio no puede estar vacio!")]
        public string PrecioVacio {
            get {
                return ((string)(this["PrecioVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El campo Valor unitario no puede estar vacio!")]
        public string ValorUnitarioVacio {
            get {
                return ((string)(this["ValorUnitarioVacio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El cliente no existe!")]
        public string ClienteNull {
            get {
                return ((string)(this["ClienteNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La Familia no existe!")]
        public string FamiliaNull {
            get {
                return ((string)(this["FamiliaNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Termino Cotizacion no existe!")]
        public string TerminoCotizacionNull {
            get {
                return ((string)(this["TerminoCotizacionNull"]));
            }
        }
    }
}
